image: node:14

stages:  
  - build 
  - test  
  - deploy
build:  
  stage: build  
  script:  
    cd /builds/ArthiBasta/Co-pilotAIML/-/tree/main/examples/walk-my-dog?ref_type=heads
    - npm install    
    - npm pack  
  artifacts:    
      paths:      
        - "examples/walk-my-dog/*.tgz"

